// Code generated by weaver. DO NOT EDIT.

package semconv

// Attribute keys from the openslo semantic convention registry.
// Metric names from the openslo semantic convention registry.
const (

	// The SLO objective expressed as a decimal value (e.g., 0.999).
	ATTRIBUTE_OPENSLO_OBJECTIVE_DECIMAL = "openslo.objective.decimal"

	// The SLO objective expressed as a percentage (e.g., 99.9).
	ATTRIBUTE_OPENSLO_OBJECTIVE_PERCENT = "openslo.objective.percent"

	// The name of the service the SLO belongs to.
	ATTRIBUTE_OPENSLO_SERVICE_NAME = "openslo.service.name"

	// The name of the SLO as defined in the OpenSlo spec.
	ATTRIBUTE_OPENSLO_SLO_NAME = "openslo.slo.name"

	// The OpenSlo API version of the SLO spec.
	ATTRIBUTE_OPENSLO_SPEC_VERSION = "openslo.spec.version"

	// The time window duration for the SLO (e.g., 28d).
	ATTRIBUTE_OPENSLO_TIMEWINDOW_DURATION = "openslo.timewindow.duration"

	// SLI error rate over a 1-day window.
	METRIC_OPENSLO_SLI_ERROR_RATE_1D = "openslo.sli.error_rate_1d"

	// SLI error rate over a 1-hour window.
	METRIC_OPENSLO_SLI_ERROR_RATE_1H = "openslo.sli.error_rate_1h"

	// SLI error rate over a 28-day window.
	METRIC_OPENSLO_SLI_ERROR_RATE_28D = "openslo.sli.error_rate_28d"

	// SLI error rate over a 2-hour window.
	METRIC_OPENSLO_SLI_ERROR_RATE_2H = "openslo.sli.error_rate_2h"

	// SLI error rate over a 30-day window.
	METRIC_OPENSLO_SLI_ERROR_RATE_30D = "openslo.sli.error_rate_30d"

	// SLI error rate over a 30-minute window.
	METRIC_OPENSLO_SLI_ERROR_RATE_30M = "openslo.sli.error_rate_30m"

	// SLI error rate over a 3-day window.
	METRIC_OPENSLO_SLI_ERROR_RATE_3D = "openslo.sli.error_rate_3d"

	// SLI error rate over a 5-minute window.
	METRIC_OPENSLO_SLI_ERROR_RATE_5M = "openslo.sli.error_rate_5m"

	// SLI error rate over a 6-hour window.
	METRIC_OPENSLO_SLI_ERROR_RATE_6H = "openslo.sli.error_rate_6h"

	// SLI error rate over a 7-day window.
	METRIC_OPENSLO_SLI_ERROR_RATE_7D = "openslo.sli.error_rate_7d"

	// The error budget calculated as 1 minus the objective.
	METRIC_OPENSLO_SLO_ERROR_BUDGET = "openslo.slo.error_budget"

	// Identifies the existence of an SLO. Always has value 1.
	METRIC_OPENSLO_SLO_INFO = "openslo.slo.info"

	// The target SLI objective (e.g., 0.999 for 99.9% availability).
	METRIC_OPENSLO_SLO_OBJECTIVE = "openslo.slo.objective"

	// The SLO time window duration expressed as a number of days.
	METRIC_OPENSLO_SLO_TIMEWINDOW_DAYS = "openslo.slo.timewindow_days"
)
