groups:
  - name: openslo-info-recordings-{{ .SloName }}
    rules:
    - record: openslo_slo_info{{ if $.IsMulti }}_unlabled{{end}}
      expr: vector(1)
      labels:
        openslo_slo_name: {{ .SloName }}
        openslo_spec_version: {{ .OpensloVersion }}
        {{- range $k, $v := .ExtraLabels }}
        {{ $k }}: {{ $v }}
        {{- end }}
    - record: openslo_slo_objective{{ if $.IsMulti }}_unlabled{{end}}
      expr: vector({{ .Objective }})
      labels:
        openslo_slo_name: {{ .SloName }}
        openslo_spec_version: {{ .OpensloVersion }}
        {{- range $k, $v := .ExtraLabels }}
        {{ $k }}: {{ $v }}
        {{- end }}
    - record: openslo_slo_timewindow_days{{ if $.IsMulti }}_unlabled{{end}}
      expr: vector({{.TimeWindowDays}})
      labels:
        openslo_slo_name: {{ .SloName }}
        openslo_spec_version: {{ .OpensloVersion }}
        {{- range $k, $v := .ExtraLabels }}
        {{ $k }}: {{ $v }}
        {{- end }}
    - record: openslo_slo_error_budget{{ if $.IsMulti }}_unlabled{{end}}
      expr: vector(1- {{.Objective}})
      labels:
        openslo_slo_name: {{ .SloName }}
        openslo_spec_version: {{ .OpensloVersion }}
        {{- range $k, $v := .ExtraLabels }}
        {{ $k }}: {{ $v }}
        {{- end }}
    - record: openslo_slo_current_burn_rate{{ if $.IsMulti }}_unlabled{{end}}
      expr: |
        openslo_sli_error_rate_5m{openslo_slo_name="{{ .SloName }}", openslo_spec_version="{{ .OpensloVersion }}"}
        / on(openslo_slo_name, openslo_spec_version) group_left
        openslo_slo_error_budget{openslo_slo_name="{{ .SloName }}", openslo_spec_version="{{ .OpensloVersion }}"}
      labels:
        openslo_slo_name: {{ .SloName }}
        openslo_spec_version: {{ .OpensloVersion }}
        {{- range $k, $v := .ExtraLabels }}
        {{ $k }}: {{ $v }}
        {{- end }}
    {{- if .PeriodWindow }}
    - record: openslo_slo_period_burn_rate{{ if $.IsMulti }}_unlabled{{end}}
      expr: |
        openslo_sli_error_rate_{{ .PeriodWindow }}{openslo_slo_name="{{ .SloName }}", openslo_spec_version="{{ .OpensloVersion }}"}
        / on(openslo_slo_name, openslo_spec_version) group_left
        openslo_slo_error_budget{openslo_slo_name="{{ .SloName }}", openslo_spec_version="{{ .OpensloVersion }}"}
      labels:
        openslo_slo_name: {{ .SloName }}
        openslo_spec_version: {{ .OpensloVersion }}
        {{- range $k, $v := .ExtraLabels }}
        {{ $k }}: {{ $v }}
        {{- end }}
    - record: openslo_slo_period_error_budget_remaining{{ if $.IsMulti }}_unlabled{{end}}
      expr: 1 - openslo_slo_period_burn_rate{{ if $.IsMulti }}_unlabled{{end}}{openslo_slo_name="{{ .SloName }}", openslo_spec_version="{{ .OpensloVersion }}"}
      labels:
        openslo_slo_name: {{ .SloName }}
        openslo_spec_version: {{ .OpensloVersion }}
        {{- range $k, $v := .ExtraLabels }}
        {{ $k }}: {{ $v }}
        {{- end }}
    {{- end }}
    {{- if .IsMulti }}
    - record: openslo_slo_info
      expr: label_join(openslo_slo_info_unlabeled{openslo_slo_name="{{ .SloName }}", openslo_spec_version="{{ .OpensloVersion }}"}, 'openslo_slo_name', '-', 'openslo_slo_name', '{{$.MultiDimensionalLabel}}')
      labels:
        openslo_spec_version: {{ .OpensloVersion }}
    - record: openslo_slo_objective
      expr: label_join(openslo_slo_objective_unlabeled{openslo_slo_name="{{ .SloName }}", openslo_spec_version="{{ .OpensloVersion }}"}, 'openslo_slo_name', '-', 'openslo_slo_name', '{{$.MultiDimensionalLabel}}')
      labels:
        openslo_spec_version: {{ .OpensloVersion }}
    - record: openslo_slo_timewindow_days
      expr: label_join(openslo_slo_timewindow_days_unlabeled{openslo_slo_name="{{ .SloName }}", openslo_spec_version="{{ .OpensloVersion }}"}, 'openslo_slo_name', '-', 'openslo_slo_name', '{{$.MultiDimensionalLabel}}')
      labels:
        openslo_spec_version: {{ .OpensloVersion }}
    - record: openslo_slo_error_budget
      expr: label_join(openslo_slo_error_budget_unlabeled{openslo_slo_name="{{ .SloName }}", openslo_spec_version="{{ .OpensloVersion }}"}, 'openslo_slo_name', '-', 'openslo_slo_name', '{{$.MultiDimensionalLabel}}')
      labels:
        openslo_spec_version: {{ .OpensloVersion }}
    - record: openslo_slo_current_burn_rate
      expr: |
        label_join(openslo_sli_error_rate_5m_unlabeled{openslo_slo_name="{{ .SloName }}", openslo_spec_version="{{ .OpensloVersion }}"}, 'openslo_slo_name', '-', 'openslo_slo_name', '{{$.MultiDimensionalLabel}}')
        / on(openslo_slo_name, openslo_spec_version) group_left
        openslo_slo_error_budget{openslo_slo_name="{{ .SloName }}", openslo_spec_version="{{ .OpensloVersion }}"}
      labels:
        openslo_spec_version: {{ .OpensloVersion }}
    {{- if .PeriodWindow }}
    - record: openslo_slo_period_burn_rate
      expr: |
        label_join(openslo_sli_error_rate_{{ .PeriodWindow }}_unlabeled{openslo_slo_name="{{ .SloName }}", openslo_spec_version="{{ .OpensloVersion }}"}, 'openslo_slo_name', '-', 'openslo_slo_name', '{{$.MultiDimensionalLabel}}')
        / on(openslo_slo_name, openslo_spec_version) group_left
        openslo_slo_error_budget{openslo_slo_name="{{ .SloName }}", openslo_spec_version="{{ .OpensloVersion }}"}
      labels:
        openslo_spec_version: {{ .OpensloVersion }}
    - record: openslo_slo_period_error_budget_remaining
      expr: 1 - openslo_slo_period_burn_rate{openslo_slo_name="{{ .SloName }}", openslo_spec_version="{{ .OpensloVersion }}"}
      labels:
        openslo_spec_version: {{ .OpensloVersion }}
    {{- end }}
    {{- end}}
  - name: openslo-sli-recordings-{{ .SloName }}
    rules:
    {{- range .WindowedPrometheusQueries }}
    - record: openslo_sli_error_rate_{{ .Window }}{{ if $.IsMulti }}_unlabeled{{end}}
      expr: {{ if contains "\n" .Query }}|
{{ .Query | indent 8 | trimSuffix "\n" }}{{ else }}{{ .Query }}{{ end }}
      labels:
        openslo_slo_name: {{ $.SloName }}
        openslo_spec_version: {{ $.OpensloVersion }}
        {{- range $k, $v := $.ExtraLabels }}
        {{ $k }}: {{ $v }}
        {{- end }}
    {{- end }}
    {{- if .IsMulti }}
    {{- range .WindowedPrometheusQueries }}
    - record: openslo_sli_error_rate_{{ .Window }}
      expr: label_join(openslo_sli_error_rate_{{ .Window }}_unlabeled{openslo_slo_name="{{ $.SloName }}", openslo_spec_version="{{ $.OpensloVersion }}"}, 'openslo_slo_name', '-', 'openslo_slo_name', '{{$.MultiDimensionalLabel}}')
      labels:
        openslo_spec_version: {{ $.OpensloVersion }}
    {{- end }}
    {{- end }}
  {{- if .AlertGroups }}
  - name: openslo-alerts-{{ .SloName }}
    rules:
    {{- range $severity, $alertData := .AlertGroups }}
    - alert: {{ $alertData.SloNamePascal }}{{ $alertData.KindPascal }}
      expr: |-
        {{- range $ti, $tier := $alertData.Tiers }}
        {{- if $ti }}
        or
        {{- end }}
        ({{- range $ci, $cond := $tier.Conditions }}
        {{- if $ci }}
        and
        {{- end }}
        {{ $cond.Expr -}}
        {{- end }})
        {{- end }}
      for: {{ $alertData.For }}
      labels:
        openslo_alert_severity: {{ $severity }}
        {{- if $alertData.NotificationTarget }}
        openslo_notification_target: {{ $alertData.NotificationTarget }}
        {{- end }}
        openslo_slo_name: {{ $.SloName }}
        openslo_spec_version: {{ $.OpensloVersion }}
        {{- range $k, $v := $.ExtraLabels }}
        {{ $k }}: {{ $v }}
        {{- end }}
      annotations:
        summary: "{{ $severity | title }} {{ $alertData.KindDescription }} alert for SLO {{ $.SloName }}"
        description: "Threshold {{ $alertData.Thresholds }} over {{ $alertData.Lookbacks }}"
    {{- end }}
  {{- end }}
