// Source of truth for the opensloctl integrity alert.
// Renders to ../rules/openslo-integrity-rules.yaml via `make -C deploy/mixins rules`.
//
// NOT generated by opensloctl - placed here so the per-SLO `<slo-name>-rules.yaml`
// generator doesn't clobber it on each `make generate`.
local recordings = [
  {
    record: 'openslo_slo_metric_missing',
    expr: |||
      (
        count by (openslo_slo_name) (openslo_slo_info)
        unless on (openslo_slo_name)
        count by (openslo_slo_name) (openslo_sli_error_rate_5m)
      ) == 1
    |||,
    labels: { openslo_alert_severity: 'page' },
  },
];

local alerts = [
  {
    alert: 'OpenSloSpecDrift',
    expr: 'openslo_slo_metric_missing == 1',
    ['for']: '10m',
    labels: {
      openslo_alert_severity: 'page',
      openslo_notification_target: 'engineers',
    },
    annotations: {
      summary: 'opensloctl: SLI metric missing for {{ $labels.openslo_slo_name }}',
      description: |||
        openslo_slo_info is registered for {{ $labels.openslo_slo_name }} but
        openslo_sli_error_rate_5m has produced no sample for the last 10m.

        Common causes:
          - service_name in the SLO spec does not match what the OpenTelemetry
            collector's service.name resource attribute actually emits.
          - le="..." in a histogram bucket query references a boundary that the
            trace-span-metrics connector does not export.
          - span_name="..." filter matches no real spans.

        Fix the selector in examples/oteldemo/specs/<file>.yaml and re-run
        `cd examples/oteldemo && make generate && make sync`.
      |||,
    },
  },
];

// Render via std.manifestYamlDoc, with quote_keys=false so YAML keys
// are emitted unquoted (the form `promtool check rules` parses). The
// `make rules` target runs jsonnet with `-S` so the resulting string is
// emitted as plain text rather than JSON-escaped.
std.manifestYamlDoc(
  {
    groups: [
      {
        name: 'openslo-integrity-recordings',
        interval: '1m',
        rules: recordings,
      },
      {
        name: 'openslo-integrity-alerts',
        rules: alerts,
      },
    ],
  },
  indent_array_in_object=false,
  quote_keys=false,
)
