apiVersion: openslo/v1
kind: AlertPolicy
metadata:
  name: checkout-page-alert
spec:
  description: Page alert for checkout error rate
  alertWhenBreaching: true
  conditions:
    - conditionRef: checkout-page
  notificationTargets:
    - targetRef: oncall-pagerduty
