apiVersion: openslo/v1
kind: AlertPolicy
metadata:
  name: checkout-page-alert
spec:
  description: Page alert for checkout error budget burn rate
  alertWhenBreaching: true
  conditions:
    - conditionRef: checkout-page
  notificationTargets:
    - targetRef: payments-pagerduty
