apiVersion: openslo/v1
kind: AlertPolicy
metadata:
  name: api-latency-ticket-policy
spec:
  alertWhenBreaching: true
  conditions:
    - conditionRef: api-latency-ticket-multi-dim
  notificationTargets:
    - targetRef: slack
